/**
 * Escreva a sua solução aqui
 * Code your solution here
 * Escriba su solución aquí
 */

with TotalGeral as (
    select c.id, c.name, c.investment, o.month,
    SUM(o.profit) over (partition by c.id order by o.month) as total_profit
    from clients as c
    inner join operations as o on c.id = o.client_id
),
FirstMonth as (
    select name, investment, month as month_of_payback,
    (total_profit - investment) as return_value,
    ROW_NUMBER() over (partition by id order by month) as number_row
    from TotalGeral
    where total_profit >= investment
)
select name, investment, month_of_payback, return_value as "return"
from FirstMonth
where number_row = 1
order by return_value desc;